"""Generate web-delivery derivatives from the landing-kit production candidates.

Reads only the files listed as production candidates in ASSET-CATALOG.md and writes
WebP derivatives into `web/`. Source files are never modified.

Run:  uv run python docs/assets/landing-kit/optimize.py
"""

from __future__ import annotations

import hashlib
import shutil
import tempfile
from dataclasses import dataclass
from pathlib import Path

from PIL import Image

KIT = Path(__file__).parent
WEB = KIT / "web"
WEB_BACKUP = KIT / ".web-backup"

# Quality is set per role. Photographic grounds tolerate more loss than line art,
# while textures still need to retain their surface detail.
PHOTO_Q = 82
ART_Q = 88
TEXTURE_Q = 86


@dataclass(frozen=True)
class Derivative:
    """One output width for one source asset."""

    source: str
    widths: tuple[int, ...]
    quality: int
    lossless: bool = False


PLAN: tuple[Derivative, ...] = (
    # Hero ground: served at full-bleed, so it needs the large widths.
    Derivative("hero-scene.jpg", (1920, 1440, 960, 640), PHOTO_Q),
    # Emblem and divider carry alpha and hard gold edges; keep them crisper.
    Derivative("hero-winged-scarab.png", (1600, 1080, 720, 480), ART_Q),
    Derivative("register-divider.png", (1600, 1080, 720), ART_Q),
    Derivative("blueprint-side-relief.png", (724, 480), ART_Q),
    # Blueprints sit at low opacity behind content; one mid width is enough.
    Derivative("blueprint-chart.png", (640, 400), ART_Q),
    Derivative("blueprint-grid.png", (640, 400), ART_Q),
    Derivative("blueprint-orbit.png", (640, 400), ART_Q),
    Derivative("blueprint-radial.png", (640, 400), ART_Q),
    # Bordered texture crops are for cover/no-repeat use; retain their native size.
    Derivative("texture-blue-stone.jpg", (512,), TEXTURE_Q),
    Derivative("texture-carved.jpg", (512,), TEXTURE_Q),
    Derivative("texture-dark-stone.jpg", (512,), TEXTURE_Q),
    Derivative("texture-gold.jpg", (512,), TEXTURE_Q),
    Derivative("texture-sandstone.jpg", (512,), TEXTURE_Q),
)


def sha256(path: Path) -> str:
    """Return the uppercase SHA-256 digest of a file."""
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


def emit(spec: Derivative, output_dir: Path) -> list[tuple[str, int, int, int]]:
    """Write every width for one source. Returns (name, w, h, bytes) per output."""
    src_path = KIT / spec.source
    src = Image.open(src_path)
    has_alpha = src.mode in ("RGBA", "LA", "P")
    src = src.convert("RGBA" if has_alpha else "RGB")
    stem = src_path.stem

    written = []
    for width in spec.widths:
        if width > src.width:
            continue
        height = round(src.height * width / src.width)
        img = src.resize((width, height), Image.LANCZOS)
        # Widest output keeps the bare stem so callers have a stable default.
        suffix = "" if width == max(spec.widths) else f"-{width}w"
        out = output_dir / f"{stem}{suffix}.webp"
        img.save(out, "WEBP", quality=spec.quality, method=6)
        written.append((out.name, width, height, out.stat().st_size))
    return written


def write_manifest(rows: list[tuple[str, int, int, int]], output_dir: Path) -> None:
    """Record an integrity row per derivative.

    The kit's README establishes the convention: a shipping raster carries a
    SHA-256 so a later reviewer can prove the served file is the reviewed one.
    A derivative needs it as much as a source does — more so, since nothing
    else records which source it came from or at what quality.
    """
    by_name = {r[0]: r for r in rows}
    lines = [
        "# Web derivative manifest",
        "",
        "Generated by `optimize.py`. Do not edit by hand — re-run the script.",
        "",
        "Each row is a WebP written into `web/` from a production candidate named in",
        "`ASSET-CATALOG.md`. Sources are never modified. A derivative inherits its",
        "source's usage rights; recording those rights is still required before any",
        "of these becomes a served runtime file.",
        "",
        "| Derivative | Source | Pixels | Bytes | Quality | SHA-256 |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for spec in PLAN:
        stem = Path(spec.source).stem
        for width in sorted(spec.widths, reverse=True):
            suffix = "" if width == max(spec.widths) else f"-{width}w"
            name = f"{stem}{suffix}.webp"
            if name not in by_name:
                continue
            _, w, h, size = by_name[name]
            digest = sha256(output_dir / name)
            lines.append(
                f"| `{name}` | `{spec.source}` | {w}×{h} | {size:,} | "
                f"{spec.quality} | `{digest}` |"
            )
    (output_dir / "MANIFEST.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def recover_interrupted_publish() -> None:
    """Restore the prior derivative set after an interrupted directory swap."""
    if not WEB_BACKUP.exists():
        return
    if WEB.exists():
        raise RuntimeError(f"refusing ambiguous publish state: {WEB} and {WEB_BACKUP} both exist")
    WEB_BACKUP.rename(WEB)


def publish(staged_web: Path) -> None:
    """Replace the complete derivative set, restoring the prior set on failure."""
    if WEB_BACKUP.exists():
        raise RuntimeError(f"refusing to overwrite recovery directory: {WEB_BACKUP}")

    had_previous = WEB.exists()
    if had_previous:
        WEB.rename(WEB_BACKUP)
    try:
        staged_web.rename(WEB)
    except BaseException:
        if had_previous:
            WEB_BACKUP.rename(WEB)
        raise

    if had_previous:
        shutil.rmtree(WEB_BACKUP)


def main() -> None:
    """Rebuild every planned derivative and its integrity manifest."""
    recover_interrupted_publish()
    with tempfile.TemporaryDirectory(dir=KIT, prefix=".landing-web-") as temp_dir:
        staged_web = Path(temp_dir) / "web"
        staged_web.mkdir()
        rows: list[tuple[str, int, int, int]] = []
        src_total = 0

        for spec in PLAN:
            src_total += (KIT / spec.source).stat().st_size
            rows.extend(emit(spec, staged_web))

        write_manifest(rows, staged_web)
        publish(staged_web)

    out_total = sum(r[3] for r in rows)
    for name, w, h, size in rows:
        print(f"{name:42s} {w:5d}x{h:<5d} {size / 1024:8.1f} KB")

    print(f"\nsources {src_total / 1024 / 1024:.2f} MB "
          f"-> derivatives {out_total / 1024 / 1024:.2f} MB "
          f"({100 * out_total / src_total:.0f}%)")
    print(f"{len(rows)} files + MANIFEST.md in {WEB}")


if __name__ == "__main__":
    main()
